sudo: required
services:
  - docker
before_install:
  - docker pull surendrajat/twrp-builder:latest
before_script:
  - cd $HOME && mkdir twrp
  - wget -q https://github.com/TwrpBuilderTests/android_device_infinix_h398/releases/download/TWRP-3.2.3-TwrpBuilder-2018-10-24_17-35/TWRP-3.2.3-TwrpBuilder-h398-2018-10-24_17-35.tar
    -O $HOME/twrp.tar
  - tar -xf twrp.tar --directory $HOME/twrp/ && rm twrp.tar
script:
  - cd $HOME/twrp/ && git clone https://github.com/TwrpBuilderTests/android_device_infinix_h398.git device/infinix/h398
  - git clone https://github.com/TwrpBuilder/android_device_generic_twrpbuilder.git device/generic/twrpbuilder
  - git clone https://github.com/omnirom/android_bootable_recovery.git bootable/recovery --depth=1
  - |
    docker run --rm -i -v "$(pwd):/root/twrp/:rw,z" surendrajat/twrp-builder bash << EOF
    cd /root/twrp/
    source build/envsetup.sh && lunch omni_h398-eng && make -j16 recoveryimage
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/h398/recovery.img $HOME/twrp/TWRP-$version-h398-$(date +"%Y%m%d").img

deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GIT_OAUTH_TOKEN_TB"
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: false
    repo: bhanuone/android_device_infinix_h398
    branch: master
branches:
  except:
    - /^(?i:untagged)-.*$/
